# Generated by Django 4.1 on 2022-09-02 20:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.FloatField(default=1662149108.351748)),
                ('modify_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('delete_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('budget', models.FloatField(default=0)),
                ('deadline', models.DateField(default=datetime.date(2022, 9, 7))),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.FloatField(default=1662149108.351748)),
                ('modify_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('delete_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('title', models.CharField(max_length=100)),
                ('acceptance_criteria', models.TextField(default=None)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='time_tracker.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkTimeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.FloatField(default=1662149108.351748)),
                ('modify_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('delete_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('start_time', models.DateTimeField(default=1662149108.357399)),
                ('doer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_record', to='time_tracker.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
