# Generated by Django 4.1 on 2022-09-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create_timestamp',
            field=models.FloatField(default=1662149165.510198),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_timestamp',
            field=models.FloatField(default=1662149165.510198),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='create_timestamp',
            field=models.FloatField(default=1662149165.510198),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='start_time',
            field=models.DateTimeField(default=1662149165.51076),
        ),
    ]
