# Generated by Django 4.1 on 2022-09-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0002_alter_project_create_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimerecord',
            name='end_time',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_timestamp',
            field=models.FloatField(default=1662151551.946525),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_timestamp',
            field=models.FloatField(default=1662151551.946525),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='create_timestamp',
            field=models.FloatField(default=1662151551.946525),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='start_time',
            field=models.FloatField(default=1662151551.947088),
        ),
    ]
