# Generated by Django 4.1 on 2022-09-04 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0003_worktimerecord_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='worktimerecord',
            name='doer',
        ),
        migrations.AlterField(
            model_name='project',
            name='create_timestamp',
            field=models.FloatField(default=1662269077.571289),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 9, 9)),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_timestamp',
            field=models.FloatField(default=1662269077.571289),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='create_timestamp',
            field=models.FloatField(default=1662269077.571289),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='start_time',
            field=models.FloatField(default=1662269077.571749),
        ),
    ]
