# Generated by Django 4.1 on 2022-09-04 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracker', '0004_remove_project_owner_remove_task_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktimerecord',
            name='day',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='worktimerecord',
            name='doer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktimerecord',
            name='month',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='worktimerecord',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_timestamp',
            field=models.FloatField(default=1662271899.179918),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_timestamp',
            field=models.FloatField(default=1662271899.179918),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='create_timestamp',
            field=models.FloatField(default=1662271899.179918),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='start_time',
            field=models.FloatField(default=1662271899.180436),
        ),
        migrations.CreateModel(
            name='TaskDailyReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.FloatField(default=1662271899.179918)),
                ('modify_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('delete_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2022)),
                ('month', models.IntegerField(default=9)),
                ('day', models.IntegerField(default=4)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.task')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDailyReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.FloatField(default=1662271899.179918)),
                ('modify_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('delete_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('total_time_seconds', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=2022)),
                ('month', models.IntegerField(default=9)),
                ('day', models.IntegerField(default=4)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
