# Generated by Django 4.1 on 2022-09-06 11:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('time_tracker', '0005_project_owner_task_assignee_worktimerecord_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_timestamp',
            field=models.FloatField(default=1662463865.066966),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(default=datetime.date(2022, 9, 11)),
        ),
        migrations.AlterField(
            model_name='projectdailyreporting',
            name='create_timestamp',
            field=models.FloatField(default=1662463865.066966),
        ),
        migrations.AlterField(
            model_name='projectdailyreporting',
            name='day',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_timestamp',
            field=models.FloatField(default=1662463865.066966),
        ),
        migrations.AlterField(
            model_name='taskdailyreporting',
            name='create_timestamp',
            field=models.FloatField(default=1662463865.066966),
        ),
        migrations.AlterField(
            model_name='taskdailyreporting',
            name='day',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='create_timestamp',
            field=models.FloatField(default=1662463865.066966),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='day',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='start_time',
            field=models.FloatField(default=1662463865.067762),
        ),
        migrations.CreateModel(
            name='InvitedMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('create_timestamp', models.FloatField(default=1662463865.066966)),
                ('modify_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('delete_timestamp', models.FloatField(blank=True, default=None, editable=False, null=True)),
                ('invitation_code', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='time_tracker.project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
