# Generated by Django 4.1 on 2022-09-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0006_project_members_alter_project_create_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedmembers',
            name='create_timestamp',
            field=models.FloatField(default=1662475357.449762),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_timestamp',
            field=models.FloatField(default=1662475357.449762),
        ),
        migrations.AlterField(
            model_name='projectdailyreporting',
            name='create_timestamp',
            field=models.FloatField(default=1662475357.449762),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_timestamp',
            field=models.FloatField(default=1662475357.449762),
        ),
        migrations.AlterField(
            model_name='taskdailyreporting',
            name='create_timestamp',
            field=models.FloatField(default=1662475357.449762),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='start_time',
            field=models.FloatField(default=1662475357.450507),
        ),
        migrations.AlterUniqueTogether(
            name='invitedmembers',
            unique_together={('email', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='worktimerecord',
            unique_together={('task', 'year', 'month', 'day', 'start_time')},
        ),
        migrations.RemoveField(
            model_name='worktimerecord',
            name='create_timestamp',
        ),
        migrations.RemoveField(
            model_name='worktimerecord',
            name='delete_timestamp',
        ),
        migrations.RemoveField(
            model_name='worktimerecord',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='worktimerecord',
            name='modify_timestamp',
        ),
    ]
