# Generated by Django 4.1 on 2022-09-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0008_alter_invitedmembers_create_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktimerecord',
            name='project',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='task_time_record', to='time_tracker.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitedmembers',
            name='create_timestamp',
            field=models.FloatField(default=1662476623.492512),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_timestamp',
            field=models.FloatField(default=1662476623.492512),
        ),
        migrations.AlterField(
            model_name='projectdailyreporting',
            name='create_timestamp',
            field=models.FloatField(default=1662476623.492512),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_timestamp',
            field=models.FloatField(default=1662476623.492512),
        ),
        migrations.AlterField(
            model_name='taskdailyreporting',
            name='create_timestamp',
            field=models.FloatField(default=1662476623.492512),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='start_time',
            field=models.FloatField(default=1662476623.493237),
        ),
    ]
