# Generated by Django 4.1 on 2022-09-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_tracker', '0009_worktimerecord_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitedmembers',
            name='create_timestamp',
            field=models.FloatField(default=1662478311.172283),
        ),
        migrations.AlterField(
            model_name='project',
            name='create_timestamp',
            field=models.FloatField(default=1662478311.172283),
        ),
        migrations.AlterField(
            model_name='projectdailyreporting',
            name='create_timestamp',
            field=models.FloatField(default=1662478311.172283),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_timestamp',
            field=models.FloatField(default=1662478311.172283),
        ),
        migrations.AlterField(
            model_name='taskdailyreporting',
            name='create_timestamp',
            field=models.FloatField(default=1662478311.172283),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='worktimerecord',
            name='start_time',
            field=models.FloatField(default=1662478311.172982),
        ),
    ]
